apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool-pod
  template:
    metadata:
      labels:
        app: pgpool-pod
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: pgpool-container
        image: docker.io/bitnami/pgpool:4.2.3-debian-10-r38
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsUser: 1001
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: PGPOOL_BACKEND_NODES
          value: 0:postgres-statefulset-0.headlessservice-postgres:5432,1:postgres-statefulset-1.headlessservice-postgres:5432,2:postgres-statefulset-2.headlessservice-postgres:5432
        - name: PGPOOL_SR_CHECK_USER
          value: "repmgr"
        - name: PGPOOL_SR_CHECK_PASSWORD
          value: "repmgr_password"
        - name: PGPOOL_SR_CHECK_DATABASE
          value: "postgres"
        - name: PGPOOL_ENABLE_LDAP
          value: "no"
        - name: PGPOOL_POSTGRES_USERNAME
          value: "postgres"
        - name: PGPOOL_POSTGRES_PASSWORD
          value: "postgres_password"
        - name: PGPOOL_ADMIN_USERNAME
          value: "admin"
        - name: PGPOOL_ADMIN_PASSWORD
          value: admin
        - name: PGPOOL_ENABLE_LOAD_BALANCING
          value: "yes"
        - name: PGPOOL_ENABLE_LOG_CONNECTIONS
          value: "no"
        - name: PGPOOL_ENABLE_LOG_HOSTNAME
          value: "yes"
        - name: PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT
          value: "no"
        - name: PGPOOL_CHILD_LIFE_TIME
          value: ""
        - name: PGPOOL_ENABLE_TLS
          value: "no"
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /opt/bitnami/scripts/pgpool/healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - bash
            - -ec
            - PGPASSWORD=${PGPOOL_POSTGRES_PASSWORD} psql -U "postgres" -d "postgres" -h /opt/bitnami/pgpool/tmp -tA -c "SELECT 1" >/dev/null
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
