apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticstack-persistent-volumne-claim
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
