apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      #slack_api_url: 'https://hooks.slack.com/services/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'

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: ashwinijadhav.aws2@gmail.com
        from: ashwinijadhav.aws3@gmail.com # Update your from mail id here
        smarthost: smtp.gmail.com:587
        auth_username: ashwinijadhav.aws3@gmail.com # Update your from mail id here
        auth_identity: ashwinijadhav.aws3@gmail.com # Update your from mail id here
        auth_password: iofhzxtrizuepogk # Update your app-password here
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert  "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
    route:
      group_wait: 10s
      group_interval: 2m
      receiver: 'slack-notifications'
      repeat_interval: 2m
      routes:
       - match:
           alertname: '*'
         receiver: 'gmail-notifications'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-02-29T18:00:27Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.26.0
    helm.sh/chart: alertmanager-1.8.0
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "12972"
  uid: 3ea23e2c-3747-416f-8113-a39e43da8982
