apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheous-ingress
spec:
  rules:
  - http:
      paths:
      - path: /prometheous
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80
