global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
receivers:
- name: 'slack-notificaions'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
route:
  group_interval: 5m
  group_wait: 10s
  receiver: 'slack-notificaions'
  repeat_interval: 3h
