apiVersion: v1
kind: Service
metadata:
  name: headlessservice-postgres
  labels:
    app: headlessservice-postgres
spec:
  selector:
    app: postgres-pod
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None

