apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volumne
  labels:
    app: postgres-persistent-volumne
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy:
  awsElasticBlockStore:
    volumeID: vol-0fafe9b771ef75a3a
    fsType: ext4
